### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by ivandelp** [axle2005/ClearMob#31]
[16:03:45] [pool-3-thread-22/ERROR] [Sponge]: The Scheduler tried to run the task clearmob-A-313 owned by Plugin{id=clearmob, name=ClearMob, version=1.12.2-2.2.3, description=An Entity Cleanup Plugin. , source=./mods/ClearMob-1.12.2-2.2.3.jar}, but an error occured.
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_222]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_222]
	at net.minecraft.world.World.func_175644_a(World.java:3040) ~[amu.class:?]
	at net.minecraft.world.World.getEntities(World.java:4372) ~[amu.class:?]
	at org.spongepowered.api.world.extent.EntityUniverse.getNearbyEntities(EntityUniverse.java:106) ~[EntityUniverse.class:1.12.2-2838-7.1.7-RC3948]
	at org.spongepowered.api.entity.Entity.getNearbyEntities(Entity.java:494) ~[Entity.class:1.12.2-2838-7.1.7-RC3948]
	at io.github.axle2005.clearmob.clearers.ClearAnimals.run(ClearAnimals.java:37) ~[ClearAnimals.class:?]
	at io.github.axle2005.clearmob.clearers.ClearEntity.run(ClearEntity.java:79) ~[ClearEntity.class:?]
	at io.github.axle2005.clearmob.clearers.ClearMain.run(ClearMain.java:24) ~[ClearMain.class:?]
	at io.github.axle2005.clearmob.ClearMob.lambda$reload$1(ClearMob.java:104) ~[ClearMob.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3948]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3948]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by axle2005** [comment]
Someone else reported this too me as well... I'm not sure why its an issue all of a sudden but I was also away on a business trip. I'll review this code in shortly

**Comment by Alfonso87639** [comment]
I have the same error
