### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by bigenergy** [axle2005/ClearMob#33]
```
[01:16:04] [pool-2-thread-15/ERROR] [Sponge]: The Scheduler tried to run the task clearmob-A-1375 owned by Plugin{id=clearmob, name=ClearMob, version=1.12.2-3.0.0, description=An Entity Cleanup Plugin. , source=/root/server/./mods/plugins/ClearMob-1.12.2-3.0.0.jar}, but an error occured.
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=pool-2-thread-15, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
        at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.9]
        at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:136) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.9]
        at net.minecraft.entity.Entity.handler$zee000$impl$createDestructionEventOnDeath(Entity.java:7469) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70106_y(Entity.java:317) ~[vg.class:?]
        at net.minecraft.entity.Entity.remove(Entity.java:4851) ~[vg.class:?]
        at io.github.axle2005.clearmob.clearers.ClearEntity.run(ClearEntity.java:73) ~[ClearEntity.class:?]
        at io.github.axle2005.clearmob.ClearMob.lambda$reload$1(ClearMob.java:138) ~[ClearMob.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.9]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

spongeforge-1.12.2-2838-7.1.9

**Comment by axle2005** [comment]
What kind of mods are you running? Could I also see your config? My test server is built against this version of SF and has no issues... 

I mean I am sure I know how to resolve this... but it really shouldn't be an issue.

**Comment by bigenergy** [comment]
the problem only occurs if resources lie on the ground

**Comment by axle2005** [comment]
So just items? or a certain thing in particular?

**Comment by bigenergy** [comment]
just items, the plugin stopped working on the latest versions of the sponge, I like all other analogues clearmob

**Comment by axle2005** [comment]
https://github.com/axle2005/ClearMob/releases/tag/3.0.1

Try using this release.

**Comment by bigenergy** [comment]
Now everything works. Thank you, I will let you know if I find anything else.
